### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dburnt** [idiomatic/HandyNotes_Achievements#28]
I've been receiving an error since 9.01..."HandyNotes_Achievements\Libs/InSeason-1.1/InSeason-1.1.lua22; attempt to call field 'GetDate' (a nil value)"

**Comment by idiomatic** [comment]
Fixed in 3ca18009639688be9fa58531f0748dfef22d2693.

You can help us by testing by using a build from [automatic builds](https://github.com/idiomatic/HandyNotes_Achievements/actions?query=workflow%3AArchive+branch%3Amaster), and reporting back results.  Alternatively, you could wait for a [release via CurseForge](https://www.curseforge.com/wow/addons/handynotes_achievements/files).
